export { default as avatar1 } from './avatar-1.png';
export { default as avatar2 } from './avatar-2.png';
export { default as avatar3 } from './avatar-3.png';
export { default as avatar4 } from './avatar-4.png';
export { default as hero } from './her.jpg';
export { default as project1 } from './project-1.jpeg';
export { default as project2 } from './project-2.jpeg';
export { default as project3 } from './project-3.jpeg';
export { default as project4 } from './project-4.jpeg';
